# -*- coding: utf-8 -*-
"""Copy of Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XC6MyGap5I0Ql7r2U7NBAH5O23pGYSIT
"""

import random
num=random.randint(1,100)
print("Random number:",num)

x=int(input("enter a value"))
while x<=6:
  print(x)
  x+=1

a = 1
b = 10

for i in range(a, b):
    if i == 5:
        break
    print(i)

for i in range(1, 20):
    if i == 15:
        continue
    print(i)

def add(a, b):
    print("sum:", a + b)
    print("sub:", a - b)
    print("multiplication:", a * b)
    print("division:", a / b)
    print("modulus:", a % b)
    print("floor division:", a // b)

# Call the function
add(10, 5)

class Sample:
    def greet(self):
        print("welcome to python world")

# Create object and call the method
obj = Sample()
obj.greet()

try:
  num=str(input("enter a string:"))
  print("you entered",num)

except ValueError:
  print("Invalid input. Please enter a string")

car = {
    "car name":"Audi",
    "car model":"Audi A3",
    "car colour":"White",
    "car mileage":"17km/l"
}
print(car["car model"])